# Generated by Django 3.0.6 on 2022-02-06 05:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.TextField(max_length=191)),
                ('food_price', models.IntegerField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to=app.models.filepath)),
            ],
        ),
    ]
